# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 011e3bea7ef954b8fff4bdf7e0d376d35f73a17e6269b0c2b8542de8957f7837ca28ee02a74f659b880cbeab5959fd8c04417795fb29ca47e480e8cec47b29f6

test:
  secret_key_base: 24a98dfc82563cd3b6b4df36e18203e3bf75eeddc7ec255c919999f50f8c45b8ce276114d8915534b5b5ff9c0065d7f2416e6b0fc105e377035c08bcf821005f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
